### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by svaksha** [stevengj/NBInclude.jl#1]
On Ubuntu-lts 32-bit, I get the following errors (for testing I deleted the .julia directory):

Version 0.5.0-dev+697 (2015-10-09 21:38 UTC)
Commit 7dcc01b\* (1 day old master)

julia> Pkg.add("NBInclude")
INFO: Initializing package repository /home/mom/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
ERROR: Base.Pkg.PkgError("unknown package NBInclude")
 [inlined code] from pkg/entry.jl:53
 in anonymous at task.jl:443
 in sync_end at ./task.jl:409
 [inlined code] from task.jl:418
 in add at pkg/entry.jl:57
 in add at pkg/entry.jl:78
 [inlined code] from promotion.jl:225
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 [inlined code] from pkg/dir.jl:25
 in add at pkg.jl:27

Thanks.

Update: Fwiw, the Clone command works `Pkg.clone("https://github.com/stevengj/NBInclude.jl.git")`, so this may be related to metadata?

**Comment by stevengj** [comment]
Wow, you are quick at finding this.   I just posted the package, and haven't had a chance to register it with the METADATA yet.     To install it manually, you need to do:

```
Pkg.add("JSON")
Pkg.add("Compat")
Pkg.close("https://github.com/stevengj/NBInclude.jl")
```

Or you could just wait a couple of days for it to appear in METADATA and for `Pkg.add` to work.

**Comment by stevengj** [comment]
See JuliaLang/METADATA.jl#3717

**Comment by svaksha** [comment]
On Sun, Oct 11, 2015 at 1:32 AM, Steven G. Johnson
notifications@github.com wrote:

> Wow, you are quick at finding this. I just posted the package, and haven't had a chance to register it with

The package seems interesting and useful - Thanks for writing this :)

the METADATA yet. To install it manually, you need to do:

> Pkg.add("JSON")
> Pkg.add("Compat")
> Pkg.close("https://github.com/stevengj/NBInclude.jl")
> 
> Or you could just wait a couple of days for it to appear in METADATA and for Pkg.add to work.

The clone command worked last night so now I can test if this works on
both py and julia NB's.

SVAKSHA ॥  http://about.me/svaksha  ॥
.

**Comment by stevengj** [comment]
It only works for Julia notebooks.  What would you want it to do for a Python notebook?
