### ISSUE TITLE
Compat with Compat

### ISSUE THREAD

**Issue by zsunberg** [stevengj/NBInclude.jl#19]
I use NBInclude in several of my packages, but lately it has started to fail because it is not compatible with Compat v3, for example

![Screenshot from 2020-02-08 19-10-18](https://user-images.githubusercontent.com/4240491/74094968-e0841300-4aa6-11ea-9fee-ea02093f4489.png)

https://travis-ci.org/JuliaPOMDP/POMDPModels.jl/jobs/647754939?utm_medium=notification&utm_source=github_status

Seems like fixing this will require upgrading to Project.toml, etc. For now I think I'm just going to have to disable the tests that use NBInclude :(

**Comment by stevengj** [comment]
We just need to make a new release that switches to Project.toml and drops Julia < 1 and Compat entirely

**Comment by stevengj** [comment]
Will be closed by https://github.com/JuliaRegistries/General/pull/9203

**Comment by zsunberg** [comment]
Wow Thanks!!
