### ISSUE TITLE
Is there a way to make PyPlots not show up?

### ISSUE THREAD

**Issue by mauro3** [stevengj/NBInclude.jl#20]
I've encountered it a few times now that I wanted to include a notebook which produces plots (with PyPlot), but the include is not for the plots it produces but for the functions it contains.  Is there a way to suppress the plot output in the included location without having to comment them out in the source notebook?

**Comment by stevengj** [comment]
You can use the `regex` keyword for this — it lets you either add a comment tag to the cells that you want to include, for example.

It might be useful to support a complementary regex for cells that you want to *exclude*, since negative regexes are a pain to construct.

**Comment by stevengj** [comment]
You could also do
```
using PyPlot
PyPlot.isjulia_display[] = false
plt."switch_backend"("Agg")
plt."ioff"()
```
maybe, to prevent PyPlot from displaying anything.

**Comment by sijow** [comment]
Here's an example to filter-out cells that contain `# nbinclude:ignore`:

```julia
@nbinclude("a.ipynb"; regex=r"^(?!.*#\s*nbinclude:ignore\b)")
```
