### ISSUE TITLE
Do not include the `__main__`

### ISSUE THREAD

**Issue by zhyiyu** [stevengj/NBInclude.jl#29]
Hi, thanks for creating this package, it is extremely helpful. I would like to call for a feature: Do not include `__main__`.

What I mean by `__main__` is the part of the notebook in which we test the current notebook. We usually do not wish to import this part into another script/notebook, as some locally defined variables might be imported, thus causing conflicts or unexpected results.

For example, say I have `test.ipynb`:

```julia
function product(a::Float64, b::Float64)
    return a*b
end

## ==== ANOTHER CELL ====

a = 2.0
b = 3.0
c = product(a, b)
```

Then in another notebook, if I do:

```julia
using HCubature
@nbinclude("test.ipynb")
println(a)
println(b)
```

I can get the values of `a` and `b` from `test.ipynb`, which is not the behaviour we usually want.

I think one can label `__main__` with `if abspath(PROGRAM_FILE) == @__FILE__`. Unfortunately the code written within this block will still be imported. It will be nice if this part can be ignored.

**Comment by stevengj** [comment]
You can already do this in a variety of ways, the simplest being to use the `regex` feature to exclude cells.

For example, if you do
```jl
@nbinclude("test.ipynb", regex=r"^(?!#\s*__MAIN__)")
```
then it will exclude any cell that has a comment line `# __MAIN__`

**Comment by zhyiyu** [comment]
Thanks, I will try this approach and let you know if I have any issues.

Although I do hope something simpler could be implemented. (Regular expressions frightens me.)

**Comment by zhyiyu** [comment]
Hi, I tried the approach you suggested: `@nbinclude("example.ipynb",regex=r"^(?!#\s*__MAIN__)")`. But I got the following error:

```shell
syntax: invalid keyword argument name "Array{Any, (2,)}[
  :regex,
  Expr(:macrocall, Symbol("@r_str"), #= Symbol("In[9]"):2 =#, "^(?!#\s*__MAIN__)")]" around In[9]:2

Stacktrace:
 [1] top-level scope
   @ In[9]:2
```

I have just updated `NBInclude` (v2.3.0), did I do something wrong?

**Comment by stevengj** [comment]
Sorry, you need a semicolon before keyword arguments in a macro:
```jl
@nbinclude("example.ipynb"; regex=r"^(?!#\s*__MAIN__)")
```

**Comment by zhyiyu** [comment]
Thanks, it worked!

**Comment by zhyiyu** [comment]
Thanks, it worked!
