### ISSUE TITLE
stack traces

### ISSUE THREAD

**Issue by simonbyrne** [stevengj/NBInclude.jl#5]
I don't know enough about Julia's internals to know if it's possible, but it would be awesome if errors gave stack traces that pointed to the appropriate notebook and cell.

**Comment by stevengj** [comment]
Don't they do this already?

(It might need to be fixed for 0.6.)

**Comment by simonbyrne** [comment]
Ah, so it does. I think I was just reading them incorrectly.

(no idea about 0.6 though)
